version: "3"

tasks:
  fmt:
    desc: Format code with rustfmt
    cmds:
      - cargo fmt

  fmt-check:
    desc: Check if code is formatted
    cmds:
      - cargo fmt -- --check

  lint:
    desc: Run linter
    cmds:
      - cargo clippy --all-targets --all-features -- -D warnings

  build-release:
    desc: Build release version
    cmds:
      - cargo build --release

  test-debug:
    desc: Run tests with debug logging
    cmds:
      - RUST_LOG=debug cargo test

  test-quiet:
    desc: Run tests quietly (no debug output)
    cmds:
      - RUST_LOG=off cargo test

  coverage:
    desc: Generate code coverage report
    cmds:
      - cargo llvm-cov --all-features --workspace --html
      - echo "Coverage report generated at target/llvm-cov/html/index.html"

  coverage-open:
    desc: Generate and open coverage report in browser
    cmds:
      - cargo llvm-cov --all-features --workspace --open

  dev:
    desc: Development workflow - format, check, test, lint
    cmds:
      - cargo fmt
      - cargo check
      - cargo test
      - cargo clippy --all-targets --all-features -- -D warnings

  build-wasm:
    desc: Build WASM bindings with wasm-pack
    cmds:
      - wasm-pack build --target web --out-dir web/pkg

  web-dev:
    desc: Start Svelte development server
    dir: web
    cmds:
      - npm run dev
