#!/usr/bin/env node

// Builds the self-contained browser bundle published as `@jolars/eunoia/web`.
//
// The default `.` entry is wasm-pack's `--target bundler` output: it does a raw
// `import ... from "*.wasm"`, which only a bundler (vite/webpack/rollup) can
// resolve. That makes it unusable from a plain `<script type="module">`, an
// Observable notebook, or a raw-file CDN. This script produces an alternative
// entry that works in all of those: a single ESM file with the WebAssembly
// module base64-inlined, exposing an explicit async `init()`.
//
// Pipeline:
//   1. wasm-pack `--target web` into a private staging dir. That target emits a
//      self-contained glue whose default export is an async init that accepts
//      raw bytes (no fetch needed when we hand it a `Uint8Array`).
//   2. Rename the `.wasm` so the glue's `new URL('eunoia_wasm_bg.wasm', …)`
//      fallback literal has no matching file — otherwise esbuild would lift it
//      out as a separate asset and defeat the single-file goal. We inline the
//      bytes ourselves under a different name.
//   3. Copy the high-level wrapper (`index.ts`) in beside the web glue so its
//      `./eunoia_wasm.js` import resolves to the web-target glue.
//   4. esbuild-bundle a tiny entry (init + re-export of the wrapper) into
//      `npm/web.js`, with the `.wasm` import inlined via the `binary` loader.
//   5. Emit a hand-written `npm/web.d.ts`.

import { execSync } from "node:child_process";
import { existsSync } from "node:fs";
import { copyFile, mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const npmDir = resolve(repoRoot, "npm");
const stage = resolve(here, ".web-build");

// ---------------------------------------------------------------------------
// 0. Ensure the wrapper's dev dependencies (esbuild, typescript) are present.
// ---------------------------------------------------------------------------

if (!existsSync(resolve(here, "node_modules", "esbuild"))) {
  console.log("Installing wrapper dev dependencies (esbuild)…");
  execSync("pnpm install --silent", { cwd: here, stdio: "inherit" });
}

// ---------------------------------------------------------------------------
// 1. wasm-pack --target web into the staging dir.
// ---------------------------------------------------------------------------

await rm(stage, { recursive: true, force: true });
await mkdir(stage, { recursive: true });

execSync(`wasm-pack build crates/eunoia-wasm --target web --out-dir ${stage}`, {
  cwd: repoRoot,
  stdio: "inherit",
});

// wasm-pack drops a .gitignore in the out dir; not needed in our staging area.
await rm(resolve(stage, ".gitignore"), { force: true });

// ---------------------------------------------------------------------------
// 2. Rename the wasm out from under the glue's fetch-fallback literal.
// ---------------------------------------------------------------------------

await copyFile(
  resolve(stage, "eunoia_wasm_bg.wasm"),
  resolve(stage, "eunoia_inline.wasm"),
);
await rm(resolve(stage, "eunoia_wasm_bg.wasm"), { force: true });

// ---------------------------------------------------------------------------
// 3. Copy the high-level wrapper beside the web glue.
// ---------------------------------------------------------------------------

await copyFile(resolve(here, "index.ts"), resolve(stage, "index.ts"));

// ---------------------------------------------------------------------------
// 4. Write the web entry and bundle it.
// ---------------------------------------------------------------------------

const webEntry = `// Generated by ts/build-web.mjs — do not edit.
import initWasm from "./eunoia_wasm.js";
import wasmBytes from "./eunoia_inline.wasm";

let pending;

/**
 * Instantiate the embedded WebAssembly module. Must be awaited once before
 * calling euler(), venn(), placeLabelsForRegions(), or placementsBbox().
 * Idempotent: repeated calls share one instantiation.
 */
export function init() {
  if (!pending) {
    pending = initWasm({ module_or_path: wasmBytes }).then(() => undefined);
  }
  return pending;
}

export * from "./index.ts";
`;
await writeFile(resolve(stage, "web-entry.ts"), webEntry);

const esbuild = await import("esbuild");
await esbuild.build({
  entryPoints: [resolve(stage, "web-entry.ts")],
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  loader: { ".wasm": "binary" },
  legalComments: "none",
  outfile: resolve(npmDir, "web.js"),
});

// ---------------------------------------------------------------------------
// 5. Type declaration: re-export the wrapper's types + declare init().
// ---------------------------------------------------------------------------

const webDts = `// Generated by ts/build-web.mjs — do not edit.
export * from "./index.js";

/**
 * Instantiate the embedded WebAssembly module. Await once before calling
 * \`euler\`, \`venn\`, \`placeLabelsForRegions\`, or \`placementsBbox\`. Idempotent.
 */
export declare function init(): Promise<void>;
`;
await writeFile(resolve(npmDir, "web.d.ts"), webDts);

// ---------------------------------------------------------------------------
// 6. Clean up the staging dir.
// ---------------------------------------------------------------------------

await rm(stage, { recursive: true, force: true });

console.log("Built npm/web.js (self-contained browser bundle) + web.d.ts");
